name: Feature Request
description: File a feature request
title: "[Feature]: "
labels: ["feature", "must-add", "type: feature"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Is this feature you'd like to see? We'd love to hear from you!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. lukeskywalker@me.com
    validations:
      required: false
  - type: textarea
    id: feature-description
    attributes:
      label: What's this feature about?
      description: Descript in plain english what the feature is about
      placeholder: What's this feature about?
    validations:
      required: true
  - type: textarea
    id: options
    attributes:
      label: Bug or Feature?
      description: Is this feature related to a bug or it's totally something new?
      placeholder: ex. You can have a feature whereby a user can...
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you using?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Opera
        - Brave
        - Arc
    validations:
      required: true
  - type: checkboxes
    id: design
    attributes:
      label: Design
      description: Is this feature related to a redesign?
      options:
        - label: Yes
          required: true
        - label: No
          required: true
  - type: textarea
    id: related-logs
    attributes:
      label: Design Image
      description: If this feature is related to a design, please provide a link to an image
      render: shell
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
